# Generated by Django 4.1.6 on 2023-03-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_statia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statia',
            new_name='New',
        ),
    ]
